on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            5.0.x
            6.0.x
      - name: Build
        run: dotnet build --configuration Release ./Community.Sextant.WinUI.sln
      - name: Test
        run: dotnet test --configuration Release --no-build ./Community.Sextant.WinUI.sln
