on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: windows-2022
    steps:
      - uses: olegtarasov/get-tag@v2.1
        id: tagName
        with:
          tagRegex: "v(.*)"
          tagRegexGroup: 1
      - uses: actions/checkout@v2
      - name: Extract release notes
        run: |
          git log --pretty=format:'%d %s' ${GITHUB_REF} | perl -pe 's| \(.*tag: v(\d+.\d+.\d+(-preview\d{3})?)(, .*?)*\)|\n## \1\n|g' > ./RELEASE-NOTES.txt; if (-! $?) { exit 1 } else { exit $LastExitCode }
      - name: Setup .NET SDKs
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            5.0.x
            6.0.x
          include-prerelease: true
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64
          vs-version: 17
          vs-prerelease: true
      - name: Build
        run: msbuild /t:build -restore /p:Configuration=Release /p:Version="$env:TAG_NAME" -m:4 Community.Sextant.WinUI.sln
        env:
          TAG_NAME: ${{ steps.tagName.outputs.tag }}
      - name: Test
        run: Get-ChildItem -Recurse -Filter "*.Tests.dll" | ? { $_.FullName -Match "bin[\\/]Release" -and $_.FullName -notmatch "ref" } | % { vstest.console.exe $_.FullName }
      - name: Pack
        run: msbuild /t:pack /p:Configuration=Release /p:OutputPath="$(Join-Path $(Get-Location) nuget)" /p:Version="$env:TAG_NAME" -m:4 ./Community.Sextant.WinUI.sln
        env:
          TAG_NAME: ${{ steps.tagName.outputs.tag }}
      - name: Attach nuget packages to Github releases
        uses: softprops/action-gh-release@v1
        with:
          files: "./nuget/*.nupkg"
          body_path: "./RELEASE-NOTES.txt"
      #- name: Push packages to Nuget registry
      #  run: dotnet nuget push $(Get-ChildItem -Path ./nuget -Filter "*.nupkg").FullName --source "https://api.nuget.org/v3/index.json" --api-key "$env:NUGET_API_KEY" --skip-duplicate --no-symbols 1
      #  env:
      #    NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
